name: First Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trigger-next:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Running First Workflow"
      - name: Trigger Second Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-second-workflow
