name: Third Workflow

on:
  repository_dispatch:
    types: [trigger-third-workflow]

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Running Third Workflow"
